<?xml version="1.0"?>
<grammar ns="https://doi.org/10.5281/zenodo.5679629#"
    xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
    <start>
        <choice>
            <notAllowed/>
            <element name="testcase">
                <optional>
                    <attribute name="phase">
                        <data type="token"/>
                    </attribute>
                </optional>
                <attribute name="expect">
                    <choice>
                        <value type="string">valid</value>
                        <value type="string">invalid</value>
                        <value type="string">error</value>
                    </choice>
                </attribute>
                <optional>
                    <element name="label">
                        <mixed>
                            <zeroOrMore>
                                <choice>
                                    <attribute>
                                    <anyName/>
                                    </attribute>
                                    <ref name="element0"/>
                                </choice>
                            </zeroOrMore>
                        </mixed>
                    </element>
                </optional>
                <element name="schemas">
                    <oneOrMore>
                        <ref name="element1"/>
                    </oneOrMore>
                </element>
                <element name="documents">
                    <oneOrMore>
                        <element name="document">
                            <attribute name="filename">
                                <data type="string"/>
                            </attribute>
                            <oneOrMore>
                                <ref name="element2"/>
                            </oneOrMore>
                        </element>
                    </oneOrMore>
                </element>
                <optional>
                    <element name="assertions">
                        <zeroOrMore>
                            <element name="assertion">
                                <attribute name="assert">
                                    <data type="string"/>
                                </attribute>
                            </element>
                        </zeroOrMore>
                    </element>
                </optional>
            </element>
        </choice>
    </start>
    <define name="element0">
        <element>
            <anyName/>
            <mixed>
                <zeroOrMore>
                    <choice>
                        <attribute>
                            <anyName/>
                        </attribute>
                        <ref name="element0"/>
                    </choice>
                </zeroOrMore>
            </mixed>
        </element>
    </define>
    <define name="element1">
        <element>
            <anyName/>
            <mixed>
                <zeroOrMore>
                    <choice>
                        <ref name="element1"/>
                        <attribute>
                            <anyName/>
                        </attribute>
                    </choice>
                </zeroOrMore>
            </mixed>
        </element>
    </define>
    <define name="element2">
        <element>
            <anyName/>
            <mixed>
                <zeroOrMore>
                    <choice>
                        <ref name="element2"/>
                        <attribute>
                            <anyName/>
                        </attribute>
                    </choice>
                </zeroOrMore>
            </mixed>
        </element>
    </define>
</grammar>
